#!/bin/bash
# $1 is jversion - j9.4 or j9.5 ...
# avoid .suffix so git/pacman preserve eol lf on windows

# install j
rm $1_linux64.tar.gz
wget -nv www.jsoftware.com/download/$1/install/$1_linux64.tar.gz
tar -zxf $1_linux64.tar.gz

# update j
rm jc
ln -s $1/bin/jconsole jc
./jc -js "load'pacman'" "'update'jpkg''" "'install'jpkg'all'" "exit''"

# put default self-signed certificates in .ssh
sudo cp $1/addons/ide/jhs/node/key.pem  .ssh
sudo cp $1/addons/ide/jhs/node/cert.pem .ssh
sudo chmod 644 .ssh/key.pem
sudo chmod 644 .ssh/cert.pem

# install nodejs
sudo yum -y install nodejs
echo `which node` > nodebin
