#!/bin/bash
# $1 is $USER for chmod
# $2 is path to current J install

# /jguest is copy of current J install
rm -f -r /jguest
mkdir /jguest
# L option follows jhs symbolic link
cp -Lr $2 /jguest/j

if [ -d /etc/letsencrypt/live/ ]
then
 d=`sudo find /etc/letsencrypt/live/ -name fullchain.pem`
else
 d=""
fi  

if [ -z "$d" ]
then
 echo 'unsigned certificate'
 fullchain=/jguest/j/addons/ide/jhs/node/cert.pem
 key=/jguest/j/addons/ide/jhs/node/key.pem
else
 echo 'letsencrypt certificate'
 fullchain=${d#s} 
 key=${fullchain::-13}privkey.pem
fi

mkdir -p jpersist 
mkdir -p .ssh/jserver
chmod 700 .ssh/jserver
chown $1:$1 .ssh/jserver
cp $fullchain .ssh/jserver/fullchain.pem
cp $key  .ssh/jserver/key.pem
chmod 600 .ssh/jserver/fullchain.pem
chmod 600 .ssh/jserver/key.pem
chown $1:$1 .ssh/jserver/fullchain.pem
chown $1:$1 .ssh/jserver/key.pem

echo $(basename $2) > "/jguest/version.txt"
