#!/bin/bash
# $1 op - $2 port - $3 timeout
# can sudo without password
# p$2 user created if required

guestpath="$(dirname "$0")"
homebase=`pwd`

case $1 in
 jhs)

  if [ ! -d /home/p$2 ]; then
    sudo useradd -m p$2
  fi

  sudo pkill -U p$2
  sudo rm -r -d -f /home/p$2/*

  # aws server may have quota (man quota) and this could limit users disk usage
  limits="--cpu=30 --nofile=1000 --fsize=1000000000"
  su -l -c "timeout $3 prlimit $limits $homebase/jc $guestpath/guest.ijs $2 &" p$2
  ;;

 break)
  echo $1 > 'opx.txt'
  echo $2 > 'portx.txt'

  su -l -c "$homebase/jc -js break\'node\' exit\'\' " p$2
  ;;

esac
  

