#!/bin/bash
# jhs   port timeout prlimit
# user  port user    restart
# break port

# can sudo without password
# jhs p$2 user created if required

# depends on /j soft link to j install folder

case $1 in
 guest)
  sudo pkill   -U p$2
  sudo userdel -r p$2
  sudo useradd -m p$2

  # aws server may have quota (man quota) and this could limit users disk usage
  # $4 "prlimit --cpu=30 --nofile=1000 --fsize=1000000000"
  su -l -c "timeout $3 $4 /jguest/j/bin/jconsole /jguest/j/addons/ide/jhs/guest/guest.ijs $2 &" p$2
  ;;

 user)
  # task to serve port is started if port not active or if $4 is restart
  p=`fuser -n tcp $2 2>/dev/null`
  if [[ $4 == "true" || ! $p ]]; then
   sudo fuser --kill -n tcp $2   
   su -l -c "/jguest/j/bin/jconsole /jguest/j/addons/ide/jhs/guest/user.ijs $2 &" $3
  fi
  ;;

 break)
  echo $1 > 'opx.txt'
  echo $2 > 'portx.txt'

  su -l -c "/jguest/j/bin/jconsole -js break\'node\' exit\'\' " p$2
  ;;

esac
  

