#!/bin/bash
# jhs   port timeout
# user  port user
# break port

# can sudo without password
# jhs p$2 user created if required

# depends on /j soft link to j install folder

case $1 in
 jhs)

  if [ ! -d /home/p$2 ]; then
    sudo useradd -m p$2
  fi

  sudo pkill -U p$2
  sudo rm -r -d -f /home/p$2/*

  # aws server may have quota (man quota) and this could limit users disk usage
  limits="--cpu=30 --nofile=1000 --fsize=1000000000"
  su -l -c "timeout $3 prlimit $limits /jguest/j/bin/jconsole /jguest/j/addons/ide/jhs/guest/guest.ijs $2 &" p$2
  ;;

 user)
  sudo fuser --kill -n tcp $2
  su -l -c "/jguest/j/bin/jconsole /jguest/j/addons/ide/jhs/guest/guest.ijs $2 &" $3
  ;;

 break)
  echo $1 > 'opx.txt'
  echo $2 > 'portx.txt'

  su -l -c "/jguest/j/bin/jconsole -js break\'node\' exit\'\' " p$2
  ;;

esac
  

